Issue 777 fix UI in mozilla firefox browser
algodex/algodex-react pull request #812
Opened 2022-10-17 21:32 UTC by IYTEC

# ℹ Overview
Fix mozilla UI

### 📝 Related Issues
- closes #777 
- closes #740 

### 🔐 Acceptance:

- [ ] `yarn test` passes

2022-10-17 23:26 UTC, atrefonas commented on components/Nav/Header/index.jsx
> -/*
Please add the copyright back

2022-10-18 05:25 UTC, IYTEC commented on components/Nav/Header/index.jsx
> -/*
Done @atrefonas

2022-10-18 17:51 UTC, atrefonas requested changes
My open orders are not showing up, even when I refresh the page. I only see them when I go to a different tab (such as order history) and back.

WYWRYK42XADLY3O62N52BOLT27DMPRA3WNBT2OBRT65N6OEZQWD4OSH6PI is my wallet for the record.

![image](https://user-images.githubusercontent.com/72869083/196507123-96e5ebe0-671a-4a3a-9fdf-367974364e2e.png)

2022-10-18 17:54 UTC, atrefonas requested changes
See comments

2022-10-20 15:35 UTC, atrefonas requested changes
Connect a wallet now looks incorrect on Chrome on my 14in Macbook. I don't see this problem on Testnet. I think it happened since you increased the font sizes.

![image](https://user-images.githubusercontent.com/72869083/196993490-b4042e16-7919-4e28-b0d2-76c262b0136b.png)

2022-10-20 15:36 UTC, atrefonas commented
Can you make reduce the font sizes in the top similar to how they were before? Doesn't have to be exactly the same. And make it so the Connect a Wallet doesn't appear on 3 lines and pops out of the box.

2022-10-20 15:37 UTC, atrefonas commented
When wallet is connected looks like this:

![image](https://user-images.githubusercontent.com/72869083/196994145-3af1da18-371b-4659-857e-e2cc11a541b8.png)

2022-10-20 15:39 UTC, atrefonas commented
Also I have 6 open orders but it isn't letting me scroll to see them.

![image](https://user-images.githubusercontent.com/72869083/196994615-17404fe8-d0e3-4cd2-bfe2-afe238cc5e98.png)

2022-10-20 18:00 UTC, atrefonas approved these changes
Works pretty well

2022-10-20 18:02 UTC, atrefonas requested changes
When my pera wallet is connected in firefox, and I refresh, it crashes the browser window

2022-10-20 18:03 UTC, atrefonas commented
> When my pera wallet is connected in firefox, and I refresh, it crashes the browser window

Also happens in Google Chrome

2022-10-20 20:27 UTC, atrefonas approved these changes

2022-10-20 20:27 UTC, merged